config/routes.rb
Rails.application.routes.draw do

  resources :lists do
      resources :telefones do
        resources :colabs
      end
  end

  resources :lists do
     patch :clear 
     put :clear
     get :clear
     post :clear
  end

  get '/autocomplete' => 'lists#autocomplete'

  resources :lis do
    collection do
      get 'get_tels', to: "lis#get_tels"
    end 
  end

  devise_for :users
	
	authenticated :user do
    	root 'admin#index', as: :authenticated_root
  	end

	root 'lists#index'
	get '/admin' => 'admin#index'
	delete '/admin' => 'admin#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/list.rb
class List < ApplicationRecord
	has_many :telefones
	has_many :colabs
  	accepts_nested_attributes_for :telefones, allow_destroy: true
  	accepts_nested_attributes_for :colabs, allow_destroy: true
	validates :setor, allow_nil: true, presence:true
	validates_associated :telefones, allow_blank: true
	validates_associated :colabs, allow_blank: true
	
	searchkick word_start: [:setor, :nome, :telefone, :ramal]

	def search_data
		data = {
			setor: setor,
			nome: colabs.map(&:nome).join(' '),
			telefone: telefones.map(&:telefone).join(' '),
			ramal: telefones.map(&:ramal).join(' '),
		}
	end

	after_commit :reindex_list

  	def reindex_list
    	List.reindex
  	end

	 def self.created_at
	 	where('created_at <= ?' , Time.now).order('created_at desc')
	 end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :autocomplete]

	def index
    @list = List.where(params[:id])
    #@colab = Colab.where(params[:id])
      if params[:keywords].present?
        @lists = List.search params[:keywords], fields: [:setor, :nome, :telefone, :ramal], misspellings: false
        #@colabs = Colab.search params[:keywords], fields: [:nome], misspellings: false
        #Searchkick.multi_search([@lists, @colabs])
        else
          @lists = List.order(:setor)
          #@lists = List.all
      end
end

  	def autocomplete
	     setor = List.search(params[:keywords], {
	     fields: [:setor], match: :word_start, limit: 5, load: false, misspellings: false
	    }).map(&:setor ).uniq

	     nome = List.search(params[:keywords], {
	     fields: [:nome], match: :word_start, limit: 5, load: false, misspellings: false
	    }).map(&:nome ).uniq

	     telefone = List.search(params[:keywords], {
	     fields: [:telefone], match: :word_start, limit: 5, load: false, misspellings: false
	    }).map(&:telefone ).uniq

	     ramal = List.search(params[:keywords], {
	     fields: [:ramal], match: :word_start, limit: 5, load: false, misspellings: false
	    }).map(&:ramal ).uniq

	     render json: (nome + setor + telefone + ramal)
  	end

	def show
		@list = List.find(params[:id])
		render :edit
	end

	def edit
		if List.exists?(id: current_user.id)
			@list = List.find(params[:id])
		else
			new
		end
	end

	def update
		@list = List.find(params[:id])
		@user = User.find(params[:id])
		
		if @user.sign_in_count == 2
				@user.update!(sign_in_count: 3)
		end
		
		if @list.update(list_params)
			redirect_to admin_path, notice:"Registro modificado com sucesso!"
		else
			render :edit
		end

	end

	def new
		@list = List.new
    	@list.telefones.build
    	@list.colabs.build
	end

	def create
		@list = List.new(list_params)
		respond_to do |format|
			if @list.save
				if signed_in? && current_user.admin?
					@colab = Colab.last
					if @colab.nome.start_with?("Adm " || "adm ")
						@colab.nome = @colab.nome[4..-1]
						@colab.update!(nome: @colab.nome)
    					resolve_new(@colab.nome.to_s)
    				else
    					resolve_new(@colab.nome.to_s)
    				end
    			end
				format.html { redirect_to admin_path, notice: 'Registro criado com sucesso!' }
				format.js
	        	format.json { render :show, status: :created, location: @list }
			else
				format.html { render :new }
	        	format.json { render json: @list.errors, status: :unprocessable_entity }
			end
		end
	end

	def clear
		@list = List.find(params[:list_id])
		@telefone = Telefone.find(params[:list_id])
		@list.update!(setor: nil)
		@telefone.update!(telefone: nil, ramal: nil)
		redirect_to admin_path, alert:"Registro removido com sucesso!"
	end

	def destroy
		@list = List.find(params[:id])
		@telefone = Telefone.find(params[:id])
		@colab = Colab.find(params[:id])
		@user = User.find(params[:id])
		@list.destroy
		@telefone.destroy
		@colab.destroy
		@user.destroy
		redirect_to admin_path, alert:"Registro removido com sucesso!"
	end

	private

	def list_params
		params.require(:list).permit(:setor, telefones_attributes:[:id, :list_id, :telefone, :ramal, :_destroy], colabs_attributes:[:id, :list_id, :nome, :_destroy])
	end
end

app/helpers/lists_helper.rb
module ListsHelper

	def format_phone(telefone)
		number_to_phone(telefone, pattern: /(\d{2})(\d{4})(\d{4})$/, area_code: true)
	end
end

app/views/lists/_form.html.erb
<div class="container2">
      <div class="middle">
            <%= simple_form_for @list do |f| %>
                  <%= render 'layouts/errors' , object: @list %>
                  <%= f.fields_for :colabs do |l| %>
                        <p>
                              <%= l.label :Nome %></br>
                              <%= l.text_field :nome, class:"form-control", style: "width:400px", readonly: true %>
                        </p>
                  <% end %>
                  <div class="field">
                  	<%= f.label :Setor %></br>
                  	<%= f.collection_select :setor, Li.order(:set), :set, :set, {prompt: "Selecione o Setor", :required => true}, style: "width:200px", class:"form-control", autofocus: true %>
                  </div>
                  <p class="form-group">
                        <%= f.fields_for :telefones do |p| %>
                              <%= p.label :Telefone %></br>
                                    <%= p.grouped_collection_select :telefone, Li.order(:set), :tels, :set, :tel, :tel, {prompt: "Selecione o Telefone" ,  :required => true}, style: "width:200px", class:"form-control" %>
                              <p>
                                    <%= p.hidden_field :ramal, readonly: true %>
                              </p>
                  	<% end %>
                  </p>
                  <p><div class="actions">
                        <% if current_page?(edit_list_path(current_user)) and current_user.sign_in_count < 3 %>
                              <%= f.submit class:'btn btn-primary' %>
                              <%= link_to 'Cancelar', admin_path, class: 'btn btn-default' %></p>
                        <% else %>
                              <p><%= f.submit "Atualizar Registro", class:'btn btn-primary' %>
                              <%= link_to 'Cancelar', admin_path, class: 'btn btn-default' %></p>
                              </br>
                              </br>
                              <% unless current_user.admin? %>
                                    <%= link_to list_clear_path(current_user), method: :clear, data:{confirm: "Tem certeza que deseja remover esse registro?"}, class:'btn btn-primary' do %>
                                      <i class="glyphicon glyphicon-remove-sign"> Remover Registro?</i>
                                    <% end %>
                              <% end %>
                        <% end %>
                  </div></p>
            <% end %>
      </div>
</div>

app/views/lists/_form2.html.erb
<div class="container2">
      <div class="middle">
            <%= simple_form_for @list do |f| %>
                  <%= render 'layouts/errors' , object: @list %>

                  <%= f.fields_for :colabs do |l| %>
                        <p>
                              <%= l.label :Nome %></br>
                              <%= l.text_field :nome, class:"typeahead2 form-control", style: "width:400px", autocomplete: "off", autofocus: true, id: "names_search", placeholder: "Pesquise aqui o nome..." %>
                        </p>
                  <% end %>
                  <div class="field">
                        <%= f.label :Setor %></br>
                        <%= f.collection_select :setor, Li.order(:set), :set, :set, {prompt: "Selecione o Setor", :required => true}, style: "width:200px", class:"form-control", autofocus: true %>
                  </div>
                  <p class="form-group">
                        <%= f.fields_for :telefones do |p| %>
                              <%= p.label :Telefone %></br>
                                    <%= p.grouped_collection_select :telefone, Li.order(:set), :tels, :set, :tel, :tel, {prompt: "Selecione o Telefone" ,  :required => true}, style: "width:200px", class:"form-control" %>
                              <p>
                                    <%= p.hidden_field :ramal, readonly: true %>
                              </p>
                        <% end %>
                  </p>
                  <p><div class="actions">
                        <p><%= f.submit class:'btn btn-primary' %>
                              <%= link_to 'Cancelar', admin_path, class: 'btn btn-default' %></p>
                  </div></p>
            <% end %>
      </div>
</div>

app/views/lists/edit.html.erb
<div class='container3'>
  <div class="middle">
      <% if current_user.sign_in_count == 2 %>
        <h2>Cadastrando Novo Registro</h2><br>
      <% else %>
        <h2>Editar Registro</h2>
      <% end %>
  </div>
</div>
  <div class="panel-body">
    <%= render 'form'%>
  </div>

app/views/lists/index.html.erb
<div class="container">
  <section class="lists">
    <% if @lists.present? %>
      <%= render 'layouts/view_list' %>
    <% else %>
      <% flash[:alert] = "Não existem registros para a busca " %>
    <% end %>
  </selection>
</div>

app/views/lists/new.html.erb
<div class='container3'>
  <div class="middle">
  	<h2>Cadastrando Novo Registro</h2>
  </div>
</div>
  <div class="panel-body">
	<%= render 'form2'%>
  </div>
</div>
</div>

app/views/lists/show.html.erb
<!--<div class="container">
<div class="jumbotron">
<article>
 	<header>
 		<p><h1><%= @list.nome %></h1></p>
 	</header>
 </article>
</div>

<%= link_to new_list_path(@list), class:'btn btn-link' do %>
 	<i class="glyphicon glyphicon-tower"> Cadastrar Lista</i>
<% end %>

<%= link_to lists_path, class:'btn btn-link' do %>
 	<i class="glyphicon glyphicon-home"> Voltar</i>
<% end %>

<%= link_to edit_list_path(@list), class:'btn btn-link' do %>
	<i class="glyphicon glyphicon-edit"> Editar</i>
<% end %>

 <%= link_to list_path(@list), method: :delete, data:{confirm: "Deseja deletar essa list?"}, class:'btn btn-link' do %>
 	<i class="glyphicon glyphicon-remove-sign"> Deletar</i>
 <% end %>

</div>-->