config/routes.rb
Rails.application.routes.draw do

  resources :lists do
      resources :telefones do
        resources :colabs
      end
  end

  resources :lists do
     patch :clear 
     put :clear
     get :clear
     post :clear
  end

  get '/autocomplete' => 'lists#autocomplete'

  resources :lis do
    collection do
      get 'get_tels', to: "lis#get_tels"
    end 
  end

  devise_for :users
	
	authenticated :user do
    	root 'admin#index', as: :authenticated_root
  	end

	root 'lists#index'
	get '/admin' => 'admin#index'
	delete '/admin' => 'admin#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/telefone.rb
class Telefone < ApplicationRecord
  belongs_to :list
  validates :telefone, allow_nil: true, presence:true
  validates :ramal, allow_blank: true, presence: true
  #validates_length_of :ramal, is:4
  #validates_format_of :telefone, with: /\A(([1-9]{2})?([1-9]{1})?([0-9]{3})?(\-)?[0-9]{4})?\Z/

  searchkick text_end: [:telefone, :ramal]

  #after_commit :reindex_list

  	def reindex_list
    	Telefone.reindex
  	end


end

app/controllers/telefones_controller.rb
class TelefonesController < ApplicationController
  #before_action :set_telefone, only: [:show, :edit, :update, :destroy]
  before_action :set_list

  # GET /telefones
  # GET /telefones.json
  def index
    @telefones = @list.telefones
  end

  # GET /telefones/1
  # GET /telefones/1.json
  def show
  end

  # GET /telefones/new
  def new
    @telefone = Telefones.new
  end

  # GET /telefones/1/edit
  def edit
  end

  # POST /telefones
  # POST /telefones.json
  def create
    @telefone = @telefone.new(telefone_params)
    respond_to do |format|
      if @telefone.save
        format.html { redirect_to admin_path, notice: 'Telefone was successfully created.' }
        format.json { render :show, status: :created, location: @telefone }
      else
        format.html { render :new }
        format.json { render json: @telefone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /telefones/1
  # PATCH/PUT /telefones/1.json
  def update
    respond_to do |format|
      if @telefone.update(telefone_params)
        format.html { redirect_to @telefone, notice: 'Telefone was successfully updated.' }
        format.json { render :show, status: :ok, location: @telefone }
      else
        format.html { render :edit }
        format.json { render json: @telefone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /telefones/1
  # DELETE /telefones/1.json
  def destroy
    @telefone.destroy
    respond_to do |format|
      format.html { redirect_to telefones_url, notice: 'Telefone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_list
      @list = List.find(params[:list_id])     
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def telefone_params
      params.require(:telefone).permit(:telefone, :ramal, :list_id)
    end
end

app/helpers/telefones_helper.rb
module TelefonesHelper
end

app/views/telefones/_form.html.erb
<%= form_with(model: telefone, local: true) do |form| %>
  <% if telefone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(telefone.errors.count, "error") %> prohibited this telefone from being saved:</h2>

      <ul>
      <% telefone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :telefone_telefone %>
  </div>

  <div class="field">
    <%= form.label :ramal %>
    <%= form.text_field :ramal, id: :telefone_ramal %>
  </div>

  <div class="field">
    <%= form.label :list_id %>
    <%= form.text_field :list_id, id: :telefone_list_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/telefones/edit.html.erb
<h1>Editing Telefone</h1>

<%= render 'form', telefone: @telefone %>

<%= link_to 'Show', @telefone %> |
<%= link_to 'Back', telefones_path %>

app/views/telefones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Telefones</h1>

<table>
  <thead>
    <tr>
      <th>Telefone</th>
      <th>Ramal</th>
      <th>List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @telefones.each do |telefone| %>
      <tr>
        <td><%= telefone.telefone %></td>
        <td><%= telefone.ramal %></td>
        <td><%= telefone.list %></td>
        <td><%= link_to 'Show', telefone %></td>
        <td><%= link_to 'Edit', edit_telefone_path(telefone) %></td>
        <td><%= link_to 'Destroy', telefone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Telefone', new_telefone_path %>

app/views/telefones/new.html.erb
<h1>New Telefone</h1>

<%= render 'form', telefone: @telefone %>

<%= link_to 'Back', telefones_path %>

app/views/telefones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Telefone:</strong>
  <%= @telefone.telefone %>
</p>

<p>
  <strong>Ramal:</strong>
  <%= @telefone.ramal %>
</p>

<p>
  <strong>List:</strong>
  <%= @telefone.list %>
</p>

<%= link_to 'Edit', edit_telefone_path(@telefone) %> |
<%= link_to 'Back', telefones_path %>