config/routes.rb
Rails.application.routes.draw do

  resources :lists do
      resources :telefones do
        resources :colabs
      end
  end

  resources :lists do
     patch :clear 
     put :clear
     get :clear
     post :clear
  end

  get '/autocomplete' => 'lists#autocomplete'

  resources :lis do
    collection do
      get 'get_tels', to: "lis#get_tels"
    end 
  end

  devise_for :users
	
	authenticated :user do
    	root 'admin#index', as: :authenticated_root
  	end

	root 'lists#index'
	get '/admin' => 'admin#index'
	delete '/admin' => 'admin#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/colab.rb
class Colab < ApplicationRecord
  belongs_to :list
  validates :nome, allow_nil: true, presence:true

  validates_format_of :nome, allow_blank: true, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
  validates_uniqueness_of :nome, allow_nil: true, message: " já existente no sistema"
  validates_length_of :nome, maximum:50
  before_validation :strip_whitespace, :only => [:nome]
  
  searchkick word_start: [:nome]

  after_commit :reindex_list

  	def reindex_list
    	Colab.reindex
  	end

    def strip_whitespace
      unless self.nome.nil?
        self.nome = self.nome.titleize
      end
    end

end

app/controllers/colabs_controller.rb
class ColabsController < ApplicationController
  #before_action :set_colab, only: [:show, :edit, :update, :destroy]
  before_action :set_list

  # GET /colabs
  # GET /colabs.json
  def index
    @colabs = @list.colabs
  end

  # GET /colabs/1
  # GET /colabs/1.json
  def show
  end

  # GET /colabs/new
  def new
    @colab = Colab.new
  end

  # GET /colabs/1/edit
  def edit
  end

  # POST /colabs
  # POST /colabs.json
  def create
    @colab = @colab.new(colab_params)
    respond_to do |format|
      if @colab.save
        format.html { redirect_to @colab, notice: 'Colab was successfully created.' }
        format.json { render :show, status: :created, location: @colab }
      else
        format.html { render :new }
        format.json { render json: @colab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colabs/1
  # PATCH/PUT /colabs/1.json
  def update
    respond_to do |format|
      if @colab.update(colab_params)
        format.html { redirect_to @colab, notice: 'Colab was successfully updated.' }
        format.json { render :show, status: :ok, location: @colab }
      else
        format.html { render :edit }
        format.json { render json: @colab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colabs/1
  # DELETE /colabs/1.json
  def destroy
    @colab.destroy
    respond_to do |format|
      format.html { redirect_to colabs_url, notice: 'Colab was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colab
      @colab = Colab.find(params[:id])
    end

    def set_list
      @list = List.find(params[:list_id])     
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def colab_params
      params.require(:colab).permit(:nome, :list_id)
    end
end

app/helpers/colabs_helper.rb
module ColabsHelper
end

app/views/colabs/_form.html.erb
<%= form_with(model: colab, local: true) do |form| %>
  <% if colab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(colab.errors.count, "error") %> prohibited this colab from being saved:</h2>

      <ul>
      <% colab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :colab_nome %>
  </div>

  <div class="field">
    <%= form.label :list_id %>
    <%= form.text_field :list_id, id: :colab_list_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/colabs/edit.html.erb
<h1>Editing Colab</h1>

<%= render 'form', colab: @colab %>

<%= link_to 'Show', @colab %> |
<%= link_to 'Back', colabs_path %>

app/views/colabs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Colabs</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colabs.each do |colab| %>
      <tr>
        <td><%= colab.nome %></td>
        <td><%= colab.list %></td>
        <td><%= link_to 'Show', colab %></td>
        <td><%= link_to 'Edit', edit_colab_path(colab) %></td>
        <td><%= link_to 'Destroy', colab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Colab', new_colab_path %>

app/views/colabs/new.html.erb
<h1>New Colab</h1>

<%= render 'form', colab: @colab %>

<%= link_to 'Back', colabs_path %>

app/views/colabs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @colab.nome %>
</p>

<p>
  <strong>List:</strong>
  <%= @colab.list %>
</p>

<%= link_to 'Edit', edit_colab_path(@colab) %> |
<%= link_to 'Back', colabs_path %>